PaintShop.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PaintShop.Web.Models
{
    public class Customer
    {
        [Required]
        [Display(Name = "Vásárló ID")]
        public int Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 5)]
        [Display(Name = "Név")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Születési idő")]
        public DateTime Date_of_birth { get; set; }

        [Required]
        [Display(Name = "Születési hely")]
        [StringLength(50, MinimumLength = 3)]
        public string Place_of_birth { get; set; }

        [Required]
        [Display(Name = "Anyja neve")]
        [StringLength(50, MinimumLength = 5)]
        public string Mothers_name { get; set; }

        [Required]
        [Display(Name = "Rendszeres vásárló")]
        public bool Regular_customer { get; set; }

    }
}

PaintShop.Web/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PaintShop.Web.Models
{
    public class CustomerViewModel
    {
        public Customer EditedCustomer { get; set; }
        public List<Customer> ListOfCustomers { get; set; }

    }
}

PaintShop.Web/Controllers/CustomersController.cs
using AutoMapper;
using Paintshop.Data;
using Paintshop.Logic;
using Paintshop.Repository;
using PaintShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Paintshop.Web.Controllers
{
    public class CustomersController : Controller
    {
        // Constructor
        Logic.Logic logic;
        IMapper mapper;
        CustomerViewModel model;

        public CustomersController()
        {
            Paintshop_dbEntities1 ctx = new Paintshop_dbEntities1();
            Customer_Repository customerRepo = new Customer_Repository();
            logic = new Logic.Logic();
            mapper = MapperFactory.CreateMapper();
            model = new CustomerViewModel();
            model.EditedCustomer = new PaintShop.Web.Models.Customer();

            var customers = logic.GetAllFromCustomers().ToList();
            model.ListOfCustomers = mapper.Map<IList<Data.Customer>, List<PaintShop.Web.Models.Customer>>(customers);
        }

        private PaintShop.Web.Models.Customer GetCustomerModel(int id)
        {
            var customer = logic.GetCustomerByID(id);
            return mapper.Map<Data.Customer, PaintShop.Web.Models.Customer>(customer);
        }

        // GET: Customers
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CustomersIndex", model);
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            return View("CustomersDetails", GetCustomerModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteFromCustomers(id) == "Instance removed successfully!")
            {
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction("Index");
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            model.EditedCustomer = GetCustomerModel(id);
            return View("CustomersIndex", model);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        public ActionResult Edit(PaintShop.Web.Models.Customer customer, string editAction)
        {
            if (ModelState.IsValid && customer != null)
            {
                List<string> paramteres = new List<string>();
                paramteres.Add(customer.Id.ToString());
                paramteres.Add(customer.Name);
                paramteres.Add(customer.Date_of_birth.ToString());
                paramteres.Add(customer.Place_of_birth);
                paramteres.Add(customer.Mothers_name);
                paramteres.Add(customer.Regular_customer.ToString());
                TempData["editResult"] = "Edit OK";

                if (editAction == "AddNew")
                {
                    logic.CreateToCustomers(paramteres);
                }
                else
                {
                    if (logic.UpdateInCustomer(paramteres) != "Instance updated successfully!")
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.EditedCustomer = customer;
                return View("CustomersIndex", model);
            }
        }
    }

}

PaintShop.Web/Views/Customers/CustomersDetails.cshtml
@model PaintShop.Web.Models.Customer

@{
    ViewBag.Title = "Customer Details";
}

<h2>Datasheet of one car</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Date_of_birth)</td>
        <td>@Html.DisplayFor(m => m.Date_of_birth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Place_of_birth)</td>
        <td>@Html.DisplayFor(m => m.Place_of_birth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Mothers_name)</td>
        <td>@Html.DisplayFor(m => m.Mothers_name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Regular_customer)</td>
        <td>@Html.DisplayFor(m => m.Regular_customer)</td>
    </tr>
</table>

PaintShop.Web/Views/Customers/CustomersEdit.cshtml
@model PaintShop.Web.Models.Customer
@{
    ViewBag.Title = "Customer Edit";
}

<br>
<div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100"
         aria-valuemin="0" aria-valuemax="100" style="width:100%">
    </div>
</div>

<h2>Customer Edit</h2>

@using (Html.BeginForm("Edit", "Customers"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Date_of_birth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Date_of_birth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Place_of_birth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Place_of_birth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Mothers_name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Mothers_name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Regular_customer)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Regular_customer)</div>

    <input type="submit" value="SEND" />
}

PaintShop.Web/Views/Customers/CustomersIndex.cshtml
@model PaintShop.Web.Models.CustomerViewModel

@{
    ViewBag.Title = "Crud Index";
}

<h2>Customers Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@Html.Partial("CustomersEdit", Model.EditedCustomer)

@Html.Partial("CustomersList", Model.ListOfCustomers)

@section scripts
{
    <script>
    $(document).ready(function () {
        $('#customerTable').DataTable({
            "pageLength": 5
        });
    });
    </script>
}

PaintShop.Web/Views/Customers/CustomersList.cshtml
@model IEnumerable<PaintShop.Web.Models.Customer>

@{
    ViewBag.Title = "Customer List";
}

<br>
<div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100"
         aria-valuemin="0" aria-valuemax="100" style="width:100%">
    </div>
</div>

<h2>Customers List</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table class="table" id="customerTable">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.First().Name)</th>
                <th>@Html.DisplayNameFor(m => m.First().Date_of_birth)</th>
                <th>@Html.DisplayNameFor(m => m.First().Place_of_birth)</th>
                <th>@Html.DisplayNameFor(m => m.First().Mothers_name)</th>
                <th>@Html.DisplayNameFor(m => m.First().Regular_customer)</th>
                <th>Datasheet</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Name)</td>
                    <td>@Html.DisplayFor(m => item.Date_of_birth)</td>
                    <td>@Html.DisplayFor(m => item.Place_of_birth)</td>
                    <td>@Html.DisplayFor(m => item.Mothers_name)</td>
                    <td>@Html.DisplayFor(m => item.Regular_customer)</td>
                    <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                    <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
                </tr>
            }
        </tbody>


    </table>
}

<br>
<div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100"
         aria-valuemin="0" aria-valuemax="100" style="width:100%">
    </div>
</div>
<br>